// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUUuCGzKK9z-yY2gHz1kvvTzhIufEkQZc',
    appId: '1:74109611224:web:fdd9c16f3b4113443f3bad',
    messagingSenderId: '74109611224',
    projectId: 'csen268-s25-g5-6be5f',
    authDomain: 'csen268-s25-g5-6be5f.firebaseapp.com',
    storageBucket: 'csen268-s25-g5-6be5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUUuCGzKK9z-yY2gHz1kvvTzhIufEkQZc',
    appId: '1:74109611224:android:fdd9c16f3b4113443f3bad',
    messagingSenderId: '74109611224',
    projectId: 'csen268-s25-g5-6be5f',
    storageBucket: 'csen268-s25-g5-6be5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUUuCGzKK9z-yY2gHz1kvvTzhIufEkQZc',
    appId: '1:74109611224:ios:fdd9c16f3b4113443f3bad',
    messagingSenderId: '74109611224',
    projectId: 'csen268-s25-g5-6be5f',
    storageBucket: 'csen268-s25-g5-6be5f.firebasestorage.app',
    iosBundleId: 'com.example.whatToEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUUuCGzKK9z-yY2gHz1kvvTzhIufEkQZc',
    appId: '1:74109611224:macos:fdd9c16f3b4113443f3bad',
    messagingSenderId: '74109611224',
    projectId: 'csen268-s25-g5-6be5f',
    storageBucket: 'csen268-s25-g5-6be5f.firebasestorage.app',
    iosBundleId: 'com.example.whatToEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUUuCGzKK9z-yY2gHz1kvvTzhIufEkQZc',
    appId: '1:74109611224:windows:fdd9c16f3b4113443f3bad',
    messagingSenderId: '74109611224',
    projectId: 'csen268-s25-g5-6be5f',
    authDomain: 'csen268-s25-g5-6be5f.firebaseapp.com',
    storageBucket: 'csen268-s25-g5-6be5f.firebasestorage.app',
  );
} 